target-version = "py39"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".venv",
    ".vscode",
    "build",
    "dist"
]

lint.ignore = ["F405"]
lint.extend-select = ["B006", "S101"]
lint.per-file-ignores = { "tests/**/*.py" = ["S101"] }
